apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-8-benchmark
  labels:
    app: camunda-8-benchmark
spec:
  selector:
    matchLabels:
      app: camunda-8-benchmark
  replicas: 4
  template:
    metadata:
      labels:
        app: camunda-8-benchmark
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: camunda-8-benchmark
          image: us-central1-docker.pkg.dev/paul-rnd/paul-benchmark-repo/paul-camunda-8-benchmark:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dasync.corePoolSize=40
                -Dasync.maxPoolSize=300
                -Dasync.queueCapacity=2000
                -Dscheduler.poolSize=60
                -Dzeebe.client.broker.gateway-address=camunda-zeebe-gateway:26500
                -Dzeebe.client.security.plaintext=true
                -Dzeebe.client.worker.max-jobs-active=2000
                -Dzeebe.client.worker.threads=500
                -Dzeebe.client.default-job-worker-stream-enabled=true
                -Dbenchmark.startPiPerSecond=300
                -Dbenchmark.taskCompletionDelay=100
                -Dbenchmark.multipleJobTypes=0
                -Denchmark.warmupPhaseDurationMillis=6000
                -Dbenchmark.startRateAdjustmentStrategy=backpressure
                -Dbenchmark.maxBackpressurePercentage=30.0
                -Dbenchmark.startPiReduceFactor=0.1
                -Dbenchmark.startPiIncreaseFactor=0
                -Dbenchmark.fixedBackOffDelay=0
                -Dbenchmark.bpmnProcessId=PerformanceWorkflow
                -Dbenchmark.startProcesses=true         
                -Dbenchmark.startWorkers=true
                -Dbenchmark.jobType=benchmark-task
                -Dbenchmark.payloadPath=classpath:bpmn/typical_payload.json
                -Dbenchmark.autoDeployProcess=true
                -Dbenchmark.bpmnResource=classpath:bpmn/PerformanceWorkflow.bpmn
          resources:
            limits:
              cpu: 5
              memory: 10Gi
            requests:
              cpu: 5
              memory: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-8-benchmark

spec:
  selector:
    app: camunda-8-benchmark
  ports:
    - port: 8088
      targetPort: 8088