# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: latest
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  elasticsearch:
    disableExporter: true

identity:
  enabled: false
  keycloak:
    enabled: false

connectors:
  enabled: false

operate:
  enabled: false

tasklist:
  enabled: false

optimize:
  enabled: false

prometheusServiceMonitor:
  enabled: true

zeebe:
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 3
      memory: 4Gi
  clusterSize: "3"
  partitionCount: "9"
  replicationFactor: "3"
  cpuThreadCount: 3
  ioThreadCount: 2
  persistenceType: disk
  pvcSize: 128Gi
  pvcStorageClassName: ssd
  logLevel: ERROR
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: "ZEEBE_BROKER_CLUSTER_MESSAGECOMPRESSION"
      value: "SNAPPY"
zeebe-gateway:
  replicas: 1
  resources:
    limits:
      cpu: 3
      memory: 4Gi
    requests:
      cpu: 3
      memory: 4Gi
  logLevel: ERROR
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "3"
    - name: ZEEBE_GATEWAY_CLUSTER_MESSAGECOMPRESSION
      value: "SNAPPY"
# ELASTIC
elasticsearch:
  enabled: false
