# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: latest
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  elasticsearch:
    disableExporter: true

identity:
  enabled: false
  keycloak:
    enabled: false

operate:
  enabled: false

tasklist:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: false

prometheusServiceMonitor:
  enabled: true

zeebe:
  resources:
    limits:
      cpu: 15
      memory: 20Gi
    requests:
      cpu: 15
      memory: 20Gi
  clusterSize: "12"
  partitionCount: "60"
  replicationFactor: "3"
  cpuThreadCount: 8
  ioThreadCount: 5
  persistenceType: disk
  pvcSize: 128Gi
  pvcStorageClassName: ssd
  logLevel: ERROR
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_CLUSTER_MESSAGECOMPRESSION
      value: "SNAPPY"
    - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
      value: "5m"
    - name: ZEEBE_BROKER_DATA_DISK_FREESPACE_REPLICATION
      value: "2GB"
    - name: ZEEBE_BROKER_DATA_DISK_FREESPACE_PROCESSING
      value: "3GB"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_ENABLED
      value: "false"
    - name: ZEEBE_BROKER_CLUSTER_RAFT_FLUSH_DELAYTIME
      value: "10s"
    - name: ZEEBE_BROKER_DATA_LOGSEGMENTSIZE
      value: "64MB"
    - name: ZEEBE_BROKER_CLUSTER_ELECTIONTIMEOUT
      value: "5000ms"
    - name: ZEEBE_BROKER_EXPERIMENTAL_MAXAPPENDSPERFOLLOWER
      value: "8"
    - name: ZEEBE_BROKER_EXPERIMENTAL_RAFT_REQUESTTIMEOUT
      value: "200ms"
      #& less than ZEEBE_BROKER_CLUSTER_ELECTIONTIMEOUT


zeebe-gateway:
  replicas: 3
  resources:
    limits:
      cpu: 15
      memory: 20Gi
    requests:
      cpu: 15
      memory: 20Gi
  logLevel: ERROR
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "12"
    - name: ZEEBE_GATEWAY_CLUSTER_MESSAGECOMPRESSION
      value: "SNAPPY"
# ELASTIC
elasticsearch:
  enabled: false
